#!/bin/bash

cd $HOME
mkdir env
mkdir data
mkdir -p .vim/bundle
mkdir -p work/src
mkdir -p work/build
mkdir -p work/ros
mkdir -p api/src
mkdir -p api/build
mkdir -p api/ros

mv Desktop env/desktop
mv Downloads download
mv Documents data/doc
mv Music data/audio
mv Pictures data/image
mv Public data/share
mv Templates mold
mv Videos data/video

cat > .config/user-dirs.dirs <<EOF
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run.
# Format is XDG_xxx_DIR="\$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="\$HOME/env/desktop"
XDG_DOWNLOAD_DIR="\$HOME/download"
XDG_TEMPLATES_DIR="\$HOME/mold"
XDG_PUBLICSHARE_DIR="\$HOME/data/share"
XDG_DOCUMENTS_DIR="\$HOME/data/doc"
XDG_MUSIC_DIR="\$HOME/data/audio"
XDG_PICTURES_DIR="\$HOME/data/image"
XDG_VIDEOS_DIR="\$HOME/data/video"
EOF

cat >> $HOME/.bashrc <<EOF

alias cds="cd $HOME/work/src"
alias cdb="cd $HOME/work/build"
alias cdr="cd $HOME/work/ros"
alias srcr="source /opt/ros/melodic/setup.bash"
EOF

sudo apt --yes purge simple-scan mtpaint pidgin qtpass texinfo noblenote libreoffice-* 2048-qt skanlite bluedevil transmission-gtk transmission-common sylpheed abiword gnumeric audacious gnome-mpv guvcview xfburn quassel trojita vlc k3b
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sudo apt update
sudo apt --yes install build-essential cmake python-dev vim git curl keepass2 xdotool cmake-curses-gui libeigen3-dev libopencv-dev libopencv-highgui-dev python3-pip ros-melodic-desktop gdb tree libgtest-dev clangd-9
sudo apt --yes upgrade
sudo rosdep init
rosdep update

sudo update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-9 100
curl -sL install-node.now.sh/lts | sudo bash

#git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
cd env
#git clone git@github.com:aneelatwork/setup.git
git clone https://github.com/aneelatwork/setup.git
ln -s $HOME/env/setup/dotfiles/vimrc $HOME/.vimrc
vim +PlugInstall

cd $HOME
git config --global user.email 'aneelatwork@gmail.com'
git config --global user.name 'Aneel Rathore'

cd /usr/src/gtest
sudo cmake CMakeLists.txt
sudo make
sudo cp lib/*.a /usr/lib/

sudo ln -s "$HOME/env/setup/build/raks-setup-build-include" "/usr/local/bin/raks-setup-build-include"
sudo ln -s "$HOME/env/setup/build/mk" "/usr/local/bin/mk"
sudo ln -s "$HOME/env/setup/build/bd" "/usr/local/bin/bd"

