#!/bin/bash

#MIT License

#Copyright (c) 2019 aneelatwork
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

cd $HOME
mkdir env
mkdir data
mkdir -p .vim/bundle
mkdir -p work/src
mkdir -p work/build
mkdir -p work/ros
mkdir -p api/src
mkdir -p api/build
mkdir -p api/ros

mv Desktop env/desktop
mv Downloads download
mv Documents data/doc
mv Music data/audio
mv Pictures data/image
mv Public data/share
mv Templates mold
mv Videos data/video

cat > .config/user-dirs.dirs <<EOF
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run.
# Format is XDG_xxx_DIR="\$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="\$HOME/env/desktop"
XDG_DOWNLOAD_DIR="\$HOME/download"
XDG_TEMPLATES_DIR="\$HOME/mold"
XDG_PUBLICSHARE_DIR="\$HOME/data/share"
XDG_DOCUMENTS_DIR="\$HOME/data/doc"
XDG_MUSIC_DIR="\$HOME/data/audio"
XDG_PICTURES_DIR="\$HOME/data/image"
XDG_VIDEOS_DIR="\$HOME/data/video"
EOF

sudo apt --yes purge simple-scan mtpaint pidgin qtpass texinfo noblenote libreoffice-* 2048-qt skanlite bluedevil transmission-gtk transmission-common sylpheed abiword gnumeric audacious gnome-mpv guvcview xfburn quassel trojita vlc k3b
sudo apt update
sudo apt --yes install build-essential cmake python-dev nvim git curl keepass2 xdotool cmake-curses-gui python3-pip gdb tree clangd-9
sudo apt --yes upgrade

sudo update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-9 100
curl -sL install-node.now.sh/lts | sudo bash

curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

src_dir="$HOME/work/src/env"
mkdir -p "$next_dir"
cd "$next_dir"
git clone https://github.com/aneelatwork/setup.git
cat ./setup/coding/init.vim | sed "s!__nvim_plugin_path__!~/.config/nvim/init.vim" > "$HOME/.config/nvim/init.vim"
nvim +PlugInstall "+CocInstall coc-clangd" "+CocInstall coc-pyright" +qall

bld_dir="$HOME/work/build/env/setup"
mkdir -p "$bld_dir"
cd "$bld_dir"
cmake "$src_dir/setup/make"
make -j 4
sudo make install


cd $HOME
git config --global user.email 'aneelatwork@gmail.com'
git config --global user.name 'Aneel Rathore'

sudo ln -s "$HOME/env/setup/build/raks-setup-build-include" "/usr/local/bin/raks-setup-build-include"
sudo ln -s "$HOME/env/setup/build/mk" "/usr/local/bin/mk"
sudo ln -s "$HOME/env/setup/build/bd" "/usr/local/bin/bd"

