#!/bin/bash

declare rep_dir bld_dir
rep_dir="$( bd r )" || exit 1
bld_dir="$( bd )" || exit 1

if [[ $1 =~ t ]]; then mkdir -p "$bld_dir"; fi
(
cd "$bld_dir"
if [[ $1 =~ c ]]; then cmake "$rep_dir" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON; fi
if [[ $1 =~ b ]]; then make -j 4; fi
if [[ $1 =~ i ]]; then sudo make install; fi
)

